### ISSUE TITLE
Undocumented colors

### ISSUE THREAD

**Issue by RubenVerg** [iiviigames/pico8-api#2]
https://pico-8.fandom.com/wiki/Palette#128..143:_Undocumented_extra_colors

**Comment by iiviigames** [comment]
Added the undocumented colors in the form of an image beside the regular palette, and haven't been checking the issues page. But this was finished ages ago!

**Comment by iiviigames** [comment]
You know what's too funny? The link you posted was - I believe - mostly taken from a a blog post I wrote on the same site. I don't blame them - it was good info!

https://pico-8.fandom.com/wiki/User_blog:Iiviigames/Piccult_Colors!
